version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv  # Prevent overwriting virtual environment
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - production
